app:
  domain: "217.154.239.23"
  port: "14587"
  uuid: "2584b733-9095-4bec-a7d5-62b473540f7a"
  xray-version: "25.10.15"
  hy2-version: "2.6.5"
  argo-version: "2025.10.0"
  argo-domain: "guowangyouxi.kiss520.dpdns.org"
  argo-token: "eyJhIjoiZWZlZjUwOTk4N2ZjNDlmMzU4YmQzYThkZTRlYmEyYzIiLCJ0IjoiOGQyMzIxNjAtMzZlYy00YjNiLWI0YzItNGY0OGUxNTgwZTczIiwicyI6Ik9HSmtNakZpWVRNdE5qY3laaTAwTkROa0xXRTBOVEV0TVRnMFltWmxOV1F5WldKaiJ9"
  remarks-prefix: "国王游戏"
